/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ProfesoresImport } from './routes/profesores'
import { Route as InscripcionesImport } from './routes/inscripciones'
import { Route as HomeImport } from './routes/Home'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const ProfesoresRoute = ProfesoresImport.update({
  id: '/profesores',
  path: '/profesores',
  getParentRoute: () => rootRoute,
} as any)

const InscripcionesRoute = InscripcionesImport.update({
  id: '/inscripciones',
  path: '/inscripciones',
  getParentRoute: () => rootRoute,
} as any)

const HomeRoute = HomeImport.update({
  id: '/Home',
  path: '/Home',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/Home': {
      id: '/Home'
      path: '/Home'
      fullPath: '/Home'
      preLoaderRoute: typeof HomeImport
      parentRoute: typeof rootRoute
    }
    '/inscripciones': {
      id: '/inscripciones'
      path: '/inscripciones'
      fullPath: '/inscripciones'
      preLoaderRoute: typeof InscripcionesImport
      parentRoute: typeof rootRoute
    }
    '/profesores': {
      id: '/profesores'
      path: '/profesores'
      fullPath: '/profesores'
      preLoaderRoute: typeof ProfesoresImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/Home': typeof HomeRoute
  '/inscripciones': typeof InscripcionesRoute
  '/profesores': typeof ProfesoresRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/Home': typeof HomeRoute
  '/inscripciones': typeof InscripcionesRoute
  '/profesores': typeof ProfesoresRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/Home': typeof HomeRoute
  '/inscripciones': typeof InscripcionesRoute
  '/profesores': typeof ProfesoresRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/Home' | '/inscripciones' | '/profesores'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/Home' | '/inscripciones' | '/profesores'
  id: '__root__' | '/' | '/Home' | '/inscripciones' | '/profesores'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HomeRoute: typeof HomeRoute
  InscripcionesRoute: typeof InscripcionesRoute
  ProfesoresRoute: typeof ProfesoresRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HomeRoute: HomeRoute,
  InscripcionesRoute: InscripcionesRoute,
  ProfesoresRoute: ProfesoresRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/Home",
        "/inscripciones",
        "/profesores"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/Home": {
      "filePath": "Home.tsx"
    },
    "/inscripciones": {
      "filePath": "inscripciones.tsx"
    },
    "/profesores": {
      "filePath": "profesores.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
